using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace System.Windows.Media
{
    public static class Colors
    {
        public static Color AliceBlue { get { return Color.FromUInt32(0xFFF0F8FF); } }
        public static Color AntiqueWhite { get { return Color.FromUInt32(0xFFFAEBD7); } }
        public static Color Aqua { get { return Color.FromUInt32(0xFF00FFFF); } }
        public static Color Aquamarine { get { return Color.FromUInt32(0xFF7FFFD4); } }
        public static Color Azure { get { return Color.FromUInt32(0xFFF0FFFF); } }
        public static Color Beige { get { return Color.FromUInt32(0xFFF5F5DC); } }
        public static Color Bisque { get { return Color.FromUInt32(0xFFFFE4C4); } }
        public static Color Black { get { return Color.FromUInt32(0xFF000000); } }
        public static Color BlanchedAlmond { get { return Color.FromUInt32(0xFFFFEBCD); } }
        public static Color Blue { get { return Color.FromUInt32(0xFF0000FF); } }
        public static Color BlueViolet { get { return Color.FromUInt32(0xFF8A2BE2); } }
        public static Color Brown { get { return Color.FromUInt32(0xFFA52A2A); } }
        public static Color BurlyWood { get { return Color.FromUInt32(0xFFDEB887); } }
        public static Color CadetBlue { get { return Color.FromUInt32(0xFF5F9EA0); } }
        public static Color Chartreuse { get { return Color.FromUInt32(0xFF7FFF00); } }
        public static Color Chocolate { get { return Color.FromUInt32(0xFFD2691E); } }
        public static Color Coral { get { return Color.FromUInt32(0xFFFF7F50); } }
        public static Color CornflowerBlue { get { return Color.FromUInt32(0xFF6495ED); } }
        public static Color Cornsilk { get { return Color.FromUInt32(0xFFFFF8DC); } }
        public static Color Crimson { get { return Color.FromUInt32(0xFFDC143C); } }
        public static Color Cyan { get { return Color.FromUInt32(0xFF00FFFF); } }
        public static Color DarkBlue { get { return Color.FromUInt32(0xFF00008B); } }
        public static Color DarkCyan { get { return Color.FromUInt32(0xFF008B8B); } }
        public static Color DarkGoldenrod { get { return Color.FromUInt32(0xFFB8860B); } }
        public static Color DarkGray { get { return Color.FromUInt32(0xFFA9A9A9); } }
        public static Color DarkGreen { get { return Color.FromUInt32(0xFF006400); } }
        public static Color DarkKhaki { get { return Color.FromUInt32(0xFFBDB76B); } }
        public static Color DarkMagenta { get { return Color.FromUInt32(0xFF8B008B); } }
        public static Color DarkOliveGreen { get { return Color.FromUInt32(0xFF556B2F); } }
        public static Color DarkOrange { get { return Color.FromUInt32(0xFFFF8C00); } }
        public static Color DarkOrchid { get { return Color.FromUInt32(0xFF9932CC); } }
        public static Color DarkRed { get { return Color.FromUInt32(0xFF8B0000); } }
        public static Color DarkSalmon { get { return Color.FromUInt32(0xFFE9967A); } }
        public static Color DarkSeaGreen { get { return Color.FromUInt32(0xFF8FBC8F); } }
        public static Color DarkSlateBlue { get { return Color.FromUInt32(0xFF483D8B); } }
        public static Color DarkSlateGray { get { return Color.FromUInt32(0xFF2F4F4F); } }
        public static Color DarkTurquoise { get { return Color.FromUInt32(0xFF00CED1); } }
        public static Color DarkViolet { get { return Color.FromUInt32(0xFF9400D3); } }
        public static Color DeepPink { get { return Color.FromUInt32(0xFFFF1493); } }
        public static Color DeepSkyBlue { get { return Color.FromUInt32(0xFF00BFFF); } }
        public static Color DimGray { get { return Color.FromUInt32(0xFF696969); } }
        public static Color DodgerBlue { get { return Color.FromUInt32(0xFF1E90FF); } }
        public static Color Firebrick { get { return Color.FromUInt32(0xFFB22222); } }
        public static Color FloralWhite { get { return Color.FromUInt32(0xFFFFFAF0); } }
        public static Color ForestGreen { get { return Color.FromUInt32(0xFF228B22); } }
        public static Color Fuchsia { get { return Color.FromUInt32(0xFFFF00FF); } }
        public static Color Gainsboro { get { return Color.FromUInt32(0xFFDCDCDC); } }
        public static Color GhostWhite { get { return Color.FromUInt32(0xFFF8F8FF); } }
        public static Color Gold { get { return Color.FromUInt32(0xFFFFD700); } }
        public static Color Goldenrod { get { return Color.FromUInt32(0xFFDAA520); } }
        public static Color Gray { get { return Color.FromUInt32(0xFF808080); } }
        public static Color Green { get { return Color.FromUInt32(0xFF008000); } }
        public static Color GreenYellow { get { return Color.FromUInt32(0xFFADFF2F); } }
        public static Color Honeydew { get { return Color.FromUInt32(0xFFF0FFF0); } }
        public static Color HotPink { get { return Color.FromUInt32(0xFFFF69B4); } }
        public static Color IndianRed { get { return Color.FromUInt32(0xFFCD5C5C); } }
        public static Color Indigo { get { return Color.FromUInt32(0xFF4B0082); } }
        public static Color Ivory { get { return Color.FromUInt32(0xFFFFFFF0); } }
        public static Color Khaki { get { return Color.FromUInt32(0xFFF0E68C); } }
        public static Color Lavender { get { return Color.FromUInt32(0xFFE6E6FA); } }
        public static Color LavenderBlush { get { return Color.FromUInt32(0xFFFFF0F5); } }
        public static Color LawnGreen { get { return Color.FromUInt32(0xFF7CFC00); } }
        public static Color LemonChiffon { get { return Color.FromUInt32(0xFFFFFACD); } }
        public static Color LightBlue { get { return Color.FromUInt32(0xFFADD8E6); } }
        public static Color LightCoral { get { return Color.FromUInt32(0xFFF08080); } }
        public static Color LightCyan { get { return Color.FromUInt32(0xFFE0FFFF); } }
        public static Color LightGoldenrodYellow { get { return Color.FromUInt32(0xFFFAFAD2); } }
        public static Color LightGray { get { return Color.FromUInt32(0xFFD3D3D3); } }
        public static Color LightGreen { get { return Color.FromUInt32(0xFF90EE90); } }
        public static Color LightPink { get { return Color.FromUInt32(0xFFFFB6C1); } }
        public static Color LightSalmon { get { return Color.FromUInt32(0xFFFFA07A); } }
        public static Color LightSeaGreen { get { return Color.FromUInt32(0xFF20B2AA); } }
        public static Color LightSkyBlue { get { return Color.FromUInt32(0xFF87CEFA); } }
        public static Color LightSlateGray { get { return Color.FromUInt32(0xFF778899); } }
        public static Color LightSteelBlue { get { return Color.FromUInt32(0xFFB0C4DE); } }
        public static Color LightYellow { get { return Color.FromUInt32(0xFFFFFFE0); } }
        public static Color Lime { get { return Color.FromUInt32(0xFF00FF00); } }
        public static Color LimeGreen { get { return Color.FromUInt32(0xFF32CD32); } }
        public static Color Linen { get { return Color.FromUInt32(0xFFFAF0E6); } }
        public static Color Magenta { get { return Color.FromUInt32(0xFFFF00FF); } }
        public static Color Maroon { get { return Color.FromUInt32(0xFF800000); } }
        public static Color MediumAquamarine { get { return Color.FromUInt32(0xFF66CDAA); } }
        public static Color MediumBlue { get { return Color.FromUInt32(0xFF0000CD); } }
        public static Color MediumOrchid { get { return Color.FromUInt32(0xFFBA55D3); } }
        public static Color MediumPurple { get { return Color.FromUInt32(0xFF9370DB); } }
        public static Color MediumSeaGreen { get { return Color.FromUInt32(0xFF3CB371); } }
        public static Color MediumSlateBlue { get { return Color.FromUInt32(0xFF7B68EE); } }
        public static Color MediumSpringGreen { get { return Color.FromUInt32(0xFF00FA9A); } }
        public static Color MediumTurquoise { get { return Color.FromUInt32(0xFF48D1CC); } }
        public static Color MediumVioletRed { get { return Color.FromUInt32(0xFFC71585); } }
        public static Color MidnightBlue { get { return Color.FromUInt32(0xFF191970); } }
        public static Color MintCream { get { return Color.FromUInt32(0xFFF5FFFA); } }
        public static Color MistyRose { get { return Color.FromUInt32(0xFFFFE4E1); } }
        public static Color Moccasin { get { return Color.FromUInt32(0xFFFFE4B5); } }
        public static Color NavajoWhite { get { return Color.FromUInt32(0xFFFFDEAD); } }
        public static Color Navy { get { return Color.FromUInt32(0xFF000080); } }
        public static Color OldLace { get { return Color.FromUInt32(0xFFFDF5E6); } }
        public static Color Olive { get { return Color.FromUInt32(0xFF808000); } }
        public static Color OliveDrab { get { return Color.FromUInt32(0xFF6B8E23); } }
        public static Color Orange { get { return Color.FromUInt32(0xFFFFA500); } }
        public static Color OrangeRed { get { return Color.FromUInt32(0xFFFF4500); } }
        public static Color Orchid { get { return Color.FromUInt32(0xFFDA70D6); } }
        public static Color PaleGoldenrod { get { return Color.FromUInt32(0xFFEEE8AA); } }
        public static Color PaleGreen { get { return Color.FromUInt32(0xFF98FB98); } }
        public static Color PaleTurquoise { get { return Color.FromUInt32(0xFFAFEEEE); } }
        public static Color PaleVioletRed { get { return Color.FromUInt32(0xFFDB7093); } }
        public static Color PapayaWhip { get { return Color.FromUInt32(0xFFFFEFD5); } }
        public static Color PeachPuff { get { return Color.FromUInt32(0xFFFFDAB9); } }
        public static Color Peru { get { return Color.FromUInt32(0xFFCD853F); } }
        public static Color Pink { get { return Color.FromUInt32(0xFFFFC0CB); } }
        public static Color Plum { get { return Color.FromUInt32(0xFFDDA0DD); } }
        public static Color PowderBlue { get { return Color.FromUInt32(0xFFB0E0E6); } }
        public static Color Purple { get { return Color.FromUInt32(0xFF800080); } }
        public static Color Red { get { return Color.FromUInt32(0xFFFF0000); } }
        public static Color RosyBrown { get { return Color.FromUInt32(0xFFBC8F8F); } }
        public static Color RoyalBlue { get { return Color.FromUInt32(0xFF4169E1); } }
        public static Color SaddleBrown { get { return Color.FromUInt32(0xFF8B4513); } }
        public static Color Salmon { get { return Color.FromUInt32(0xFFFA8072); } }
        public static Color SandyBrown { get { return Color.FromUInt32(0xFFF4A460); } }
        public static Color SeaGreen { get { return Color.FromUInt32(0xFF2E8B57); } }
        public static Color SeaShell { get { return Color.FromUInt32(0xFFFFF5EE); } }
        public static Color Sienna { get { return Color.FromUInt32(0xFFA0522D); } }
        public static Color Silver { get { return Color.FromUInt32(0xFFC0C0C0); } }
        public static Color SkyBlue { get { return Color.FromUInt32(0xFF87CEEB); } }
        public static Color SlateBlue { get { return Color.FromUInt32(0xFF6A5ACD); } }
        public static Color SlateGray { get { return Color.FromUInt32(0xFF708090); } }
        public static Color Snow { get { return Color.FromUInt32(0xFFFFFAFA); } }
        public static Color SpringGreen { get { return Color.FromUInt32(0xFF00FF7F); } }
        public static Color SteelBlue { get { return Color.FromUInt32(0xFF4682B4); } }
        public static Color Tan { get { return Color.FromUInt32(0xFFD2B48C); } }
        public static Color Teal { get { return Color.FromUInt32(0xFF008080); } }
        public static Color Thistle { get { return Color.FromUInt32(0xFFD8BFD8); } }
        public static Color Tomato { get { return Color.FromUInt32(0xFFFF6347); } }
        public static Color Transparent { get { return Color.FromUInt32(0x00FFFFFF); } }
        public static Color Turquoise { get { return Color.FromUInt32(0xFF40E0D0); } }
        public static Color Violet { get { return Color.FromUInt32(0xFFEE82EE); } }
        public static Color Wheat { get { return Color.FromUInt32(0xFFF5DEB3); } }
        public static Color White { get { return Color.FromUInt32(0xFFFFFFFF); } }
        public static Color WhiteSmoke { get { return Color.FromUInt32(0xFFF5F5F5); } }
        public static Color Yellow { get { return Color.FromUInt32(0xFFFFFF00); } }
        public static Color YellowGreen { get { return Color.FromUInt32(0xFF9ACD32); } }
    }
}
